### PR TITLE
Major Code Cleanup

### PR DESCRIPTION
**Pull request by cdrice26**
I've completed major code cleanup on the SHARC project by doing the following:
- Split the backend up into multiple files - each file is a separate route (called a "blueprint") on the api, and then there are individual routes defined in those files. Each file needs to import ```mysql``` and the configs they need from ```configs.py``` and ```extensions.py```. Each blueprint is essentially a category of routes.
- Added documentation comments to both the backend and frontend (thanks AI). I didn't do the ```createEvent``` route on either end since it's not done yet.
- Added authentication requirements on all routes (except the ```createEvent``` route).
- Normalized URL style.
- Replaced hardcoded URLs on the frontend with an environment variable that changes when building for production.
- Fixed some bugs and performance issues on the frontend.
- Set the default filters to more sensible defaults than "All".

Please check and make sure all your stuff works, this is a major enough change I don't want to just merge it right away. Once merged, please do the following with all future code:
- Include documentation comments. Usually AI does a pretty good job creating these.
- Put all future backend routes in the appropriate blueprint. You can see how they are created in ```main.py``` and each of the route files if you feel your route needs a new category. Note that all routes in a blueprint have the url that is the concatenation of the base url defined in ```main.py``` and the url you define in ```@blueprint.route()```.
- Use the environment variable as the base URL for all ```fetch``` calls from the frontend. You can check any existing ```fetch``` call to see what you need to do for that.
- Define all server-side API routes with a hyphenated url path (e.g. ```/api/your-api-route```).

### CODE REVIEW

**Comment by chengeu25** [comment]
i approve

**Review by chengeu25 — APPROVED** [review]

**Comment by garretvan** [comment]
THIS LOOKS COOL

**Review by mdmerlo1 — APPROVED** [review]
Looks good to me

**Review by garretvan — APPROVED** [review]
Looks good my babes

**Pull request merged**
